### ISSUE TITLE
是否添加对OneBot的支持

### ISSUE THREAD

**Issue by 100luo-6** [RegadPoleCN/PlumBot#29]
现在使用的是LLOneBot

**Comment by 100luo-6** [comment]
velocity 报错
[01:29:05 ERROR]: java.lang.NullPointerException
[01:29:05 ERROR]:       at java.base/java.util.Objects.requireNonNull(Objects.java:209)
[01:29:05 ERROR]:       at java.base/java.nio.file.Files.copy(Files.java:3128)
[01:29:05 ERROR]:       at me.regadpole.plumbot.config.VelocityConfig.loadConfig(VelocityConfig.java:56)
[01:29:05 ERROR]:       at me.regadpole.plumbot.PlumBot.<init>(PlumBot.java:63)
[01:29:05 ERROR]:       at me.regadpole.plumbot.PlumBot$$FastClassByGuice$$c188d.GUICE$TRAMPOLINE(<generated>)
[01:29:05 ERROR]:       at me.regadpole.plumbot.PlumBot$$FastClassByGuice$$c188d.apply(<generated>)
[01:29:05 ERROR]:       at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[01:29:05 ERROR]:       at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[01:29:05 ERROR]:       at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[01:29:05 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
[01:29:05 ERROR]:       at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[01:29:05 ERROR]:       at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[01:29:05 ERROR]:       at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[01:29:05 ERROR]:       at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
[01:29:05 ERROR]:       at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
[01:29:05 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:134)
[01:29:05 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155)
[01:29:05 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:364)
[01:29:05 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241)
[01:29:05 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:70)
[01:29:05 ERROR]: Can't create plugin plumbot
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NullPointerException: repoUrl
  at PlumBot.<init>(PlumBot.java:51)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating PlumBot

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
PlumBot:              "me.regadpole.plumbot.PlumBot"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:134) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:364) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
Caused by: java.lang.NullPointerException: repoUrl
        at java.base/java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at me.regadpole.plumbot.internal.maven.LibraryLoader$Dependency.<init>(LibraryLoader.java:138) ~[?:?]
        at me.regadpole.plumbot.internal.maven.LibraryLoader.load(LibraryLoader.java:83) ~[?:?]
        at me.regadpole.plumbot.internal.maven.LibraryLoader.load(LibraryLoader.java:79) ~[?:?]
        at me.regadpole.plumbot.internal.maven.LibraryLoader.loadAll(LibraryLoader.java:73) ~[?:?]
        at me.regadpole.plumbot.PlumBot.<init>(PlumBot.java:70) ~[?:?]
        at me.regadpole.plumbot.PlumBot$$FastClassByGuice$$c188d.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at me.regadpole.plumbot.PlumBot$$FastClassByGuice$$c188d.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-365.jar:3.3.0-SNAPSHOT (git-af09677f-b365)]
        ... 6 more

**Comment by RegadPoleCN** [comment]
这个是插件的问题，可以去actions里面尝试使用最新版的

**Comment by RegadPoleCN** [comment]
fixed
