### ISSUE TITLE
昨天的 2.0 版本报错了

### ISSUE THREAD

**Issue by xiaofengv233** [RegadPoleCN/PlumBot#47]
[PlumBot] Enabling PlumBot v2.0.0
[11:04:46 ERROR]: Error occurred while enabling PlumBot v2.0.0 (Is it up to date?)
kotlin1822.UninitializedPropertyAccessException: lateinit property config has not been initialized
        at PlumBot-2.0.0.jar/me.regadpole.plumbot.PlumBot.onEnable(PlumBot.kt:40) ~[PlumBot-2.0.0.jar:?]
        at PlumBot-2.0.0.jar/me.regadpole.plumbot.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:88) ~[PlumBot-2.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:04:46 INFO]: [PlumBot] Disabling PlumBot v2.0.0
[11:04:46 ERROR]: Error occurred while disabling PlumBot v2.0.0
kotlin1822.UninitializedPropertyAccessException: lateinit property bot has not been initialized
        at PlumBot-2.0.0.jar/me.regadpole.plumbot.PlumBot.onDisable(PlumBot.kt:74) ~[PlumBot-2.0.0.jar:?]
        at PlumBot-2.0.0.jar/me.regadpole.plumbot.taboolib.platform.BukkitPlugin.onDisable(BukkitPlugin.java:114) ~[PlumBot-2.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2309-be61a07]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by RegadPoleCN** [comment]
v2还没写完别急着用
